package no.nav.klage.kodeverk.hjemmel

import no.nav.klage.kodeverk.hjemmel.Hjemmel.*
import no.nav.klage.kodeverk.ytelse.Ytelse

data class HjemmelAndUtfasesStatus(
    val hjemmel: Hjemmel,
    val utfases: Boolean = false,
)

val hjemlerGRU = listOf(
    HjemmelAndUtfasesStatus(FTRL_6_2),
    HjemmelAndUtfasesStatus(FTRL_6_3),
    HjemmelAndUtfasesStatus(FTRL_6_3_A),
    HjemmelAndUtfasesStatus(FTRL_6_3_B),
    HjemmelAndUtfasesStatus(FTRL_6_3_C),
    HjemmelAndUtfasesStatus(FTRL_6_3_F),
    HjemmelAndUtfasesStatus(FTRL_6_3_G),
    HjemmelAndUtfasesStatus(FTRL_6_3_H),
    HjemmelAndUtfasesStatus(FTRL_6_4),
    HjemmelAndUtfasesStatus(FTRL_6_5),
    HjemmelAndUtfasesStatus(FTRL_6_6),
    HjemmelAndUtfasesStatus(FTRL_6_7),
    HjemmelAndUtfasesStatus(FTRL_6_8),
    HjemmelAndUtfasesStatus(FTRL_21_4),
    HjemmelAndUtfasesStatus(FTRL_21_7),
    HjemmelAndUtfasesStatus(FTRL_21_12),
    HjemmelAndUtfasesStatus(FTRL_22_12),
    HjemmelAndUtfasesStatus(FTRL_22_13),
    HjemmelAndUtfasesStatus(FTRL_22_14),
    HjemmelAndUtfasesStatus(FTRL_22_15),
    HjemmelAndUtfasesStatus(FTRL_22_17),

    HjemmelAndUtfasesStatus(FVL_30),
    HjemmelAndUtfasesStatus(FVL_31),
    HjemmelAndUtfasesStatus(FVL_32),
    HjemmelAndUtfasesStatus(FVL_33),
)

val hjemlerYRK = listOf(
    HjemmelAndUtfasesStatus(FTRL_13_3_1),
    HjemmelAndUtfasesStatus(FTRL_13_3_2),
    HjemmelAndUtfasesStatus(FTRL_13_3_FS),
    HjemmelAndUtfasesStatus(FTRL_13_4),
    HjemmelAndUtfasesStatus(FTRL_13_6),
    HjemmelAndUtfasesStatus(FTRL_13_8),
    HjemmelAndUtfasesStatus(FTRL_13_10),
    HjemmelAndUtfasesStatus(FTRL_13_17),
    HjemmelAndUtfasesStatus(FTRL_21_12),

    HjemmelAndUtfasesStatus(TRRL_9),
)

/**
 * Used for innsending, search and innstillinger
 */

val ytelseToHjemler = mapOf(
    Ytelse.ENF_ENF to listOf(
        HjemmelAndUtfasesStatus(FTRL_15_2),
        HjemmelAndUtfasesStatus(FTRL_15_3),
        HjemmelAndUtfasesStatus(FTRL_15_4),
        HjemmelAndUtfasesStatus(FTRL_15_5),
        HjemmelAndUtfasesStatus(FTRL_15_6),
        HjemmelAndUtfasesStatus(FTRL_15_8),
        HjemmelAndUtfasesStatus(FTRL_15_9),
        HjemmelAndUtfasesStatus(FTRL_15_10),
        HjemmelAndUtfasesStatus(FTRL_15_11),
        HjemmelAndUtfasesStatus(FTRL_15_12),
        HjemmelAndUtfasesStatus(FTRL_15_13),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),
    Ytelse.BAR_BAR to listOf(
        HjemmelAndUtfasesStatus(BTRL_2),
        HjemmelAndUtfasesStatus(BTRL_4),
        HjemmelAndUtfasesStatus(BTRL_5),
        HjemmelAndUtfasesStatus(BTRL_9),
        HjemmelAndUtfasesStatus(BTRL_10),
        HjemmelAndUtfasesStatus(BTRL_11),
        HjemmelAndUtfasesStatus(BTRL_12),
        HjemmelAndUtfasesStatus(BTRL_13),
        HjemmelAndUtfasesStatus(BTRL_14),
        HjemmelAndUtfasesStatus(BTRL_15),
        HjemmelAndUtfasesStatus(BTRL_17),
        HjemmelAndUtfasesStatus(BTRL_18),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(EOES_AVTALEN),
        HjemmelAndUtfasesStatus(NORDISK_KONVENSJON),
        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),
    ),

    Ytelse.KON_KON to listOf(
        HjemmelAndUtfasesStatus(KONTSL_1A),
        HjemmelAndUtfasesStatus(KONTSL_2),
        HjemmelAndUtfasesStatus(KONTSL_3),
        HjemmelAndUtfasesStatus(KONTSL_3A),
        HjemmelAndUtfasesStatus(KONTSL_4),
        HjemmelAndUtfasesStatus(KONTSL_6),
        HjemmelAndUtfasesStatus(KONTSL_7),
        HjemmelAndUtfasesStatus(KONTSL_8),
        HjemmelAndUtfasesStatus(KONTSL_9),
        HjemmelAndUtfasesStatus(KONTSL_10),
        HjemmelAndUtfasesStatus(KONTSL_11),
        HjemmelAndUtfasesStatus(KONTSL_12),
        HjemmelAndUtfasesStatus(KONTSL_13),
        HjemmelAndUtfasesStatus(KONTSL_14),
        HjemmelAndUtfasesStatus(KONTSL_16),
        HjemmelAndUtfasesStatus(KONTSL_17),
        HjemmelAndUtfasesStatus(KONTSL_19),
        HjemmelAndUtfasesStatus(KONTSL_22),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_34),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_36),
        HjemmelAndUtfasesStatus(EOES_AVTALEN),
        HjemmelAndUtfasesStatus(NORDISK_KONVENSJON),
        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),
    ),

    Ytelse.OMS_OLP to listOf(
        HjemmelAndUtfasesStatus(FTRL_9_2),
        HjemmelAndUtfasesStatus(FTRL_9_3),
        HjemmelAndUtfasesStatus(FTRL_9_5),
        HjemmelAndUtfasesStatus(FTRL_9_6),
        HjemmelAndUtfasesStatus(FTRL_9_8),
        HjemmelAndUtfasesStatus(FTRL_9_9),
        HjemmelAndUtfasesStatus(FTRL_9_10),
        HjemmelAndUtfasesStatus(FTRL_9_11),
        HjemmelAndUtfasesStatus(FTRL_9_13),
        HjemmelAndUtfasesStatus(FTRL_9_14),
        HjemmelAndUtfasesStatus(FTRL_9_15),
        HjemmelAndUtfasesStatus(FTRL_9_16),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),
    Ytelse.OMS_OMP to listOf(
        HjemmelAndUtfasesStatus(FTRL_9_2),
        HjemmelAndUtfasesStatus(FTRL_9_3),
        HjemmelAndUtfasesStatus(FTRL_9_5),
        HjemmelAndUtfasesStatus(FTRL_9_6),
        HjemmelAndUtfasesStatus(FTRL_9_8),
        HjemmelAndUtfasesStatus(FTRL_9_9),
        HjemmelAndUtfasesStatus(FTRL_9_10),
        HjemmelAndUtfasesStatus(FTRL_9_11),
        HjemmelAndUtfasesStatus(FTRL_9_13),
        HjemmelAndUtfasesStatus(FTRL_9_14),
        HjemmelAndUtfasesStatus(FTRL_9_15),
        HjemmelAndUtfasesStatus(FTRL_9_16),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),
    Ytelse.OMS_PLS to listOf(
        HjemmelAndUtfasesStatus(FTRL_9_2),
        HjemmelAndUtfasesStatus(FTRL_9_3),
        HjemmelAndUtfasesStatus(FTRL_9_5),
        HjemmelAndUtfasesStatus(FTRL_9_6),
        HjemmelAndUtfasesStatus(FTRL_9_8),
        HjemmelAndUtfasesStatus(FTRL_9_9),
        HjemmelAndUtfasesStatus(FTRL_9_10),
        HjemmelAndUtfasesStatus(FTRL_9_11),
        HjemmelAndUtfasesStatus(FTRL_9_13),
        HjemmelAndUtfasesStatus(FTRL_9_14),
        HjemmelAndUtfasesStatus(FTRL_9_15),
        HjemmelAndUtfasesStatus(FTRL_9_16),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),
    Ytelse.OMS_PSB to listOf(
        HjemmelAndUtfasesStatus(FTRL_9_2),
        HjemmelAndUtfasesStatus(FTRL_9_3),
        HjemmelAndUtfasesStatus(FTRL_9_5),
        HjemmelAndUtfasesStatus(FTRL_9_6),
        HjemmelAndUtfasesStatus(FTRL_9_8),
        HjemmelAndUtfasesStatus(FTRL_9_9),
        HjemmelAndUtfasesStatus(FTRL_9_10),
        HjemmelAndUtfasesStatus(FTRL_9_11),
        HjemmelAndUtfasesStatus(FTRL_9_13),
        HjemmelAndUtfasesStatus(FTRL_9_14),
        HjemmelAndUtfasesStatus(FTRL_9_15),
        HjemmelAndUtfasesStatus(FTRL_9_16),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),

    Ytelse.SYK_SYK to listOf(
        HjemmelAndUtfasesStatus(FTRL_8_1),
        HjemmelAndUtfasesStatus(FTRL_8_2),
        HjemmelAndUtfasesStatus(FTRL_8_3),
        HjemmelAndUtfasesStatus(FTRL_8_4, true),
        HjemmelAndUtfasesStatus(FTRL_8_4_1),
        HjemmelAndUtfasesStatus(FTRL_8_4_2),
        HjemmelAndUtfasesStatus(FTRL_8_4_3),
        HjemmelAndUtfasesStatus(FTRL_8_4_PILOT_22_15, true),
        HjemmelAndUtfasesStatus(FTRL_8_5),
        HjemmelAndUtfasesStatus(FTRL_8_6),
        HjemmelAndUtfasesStatus(FTRL_8_7),
        HjemmelAndUtfasesStatus(FTRL_8_7_PILOT, true),
        HjemmelAndUtfasesStatus(FTRL_8_8),
        HjemmelAndUtfasesStatus(FTRL_8_9),
        HjemmelAndUtfasesStatus(FTRL_8_10),
        HjemmelAndUtfasesStatus(FTRL_8_11),
        HjemmelAndUtfasesStatus(FTRL_8_12),
        HjemmelAndUtfasesStatus(FTRL_8_13),
        HjemmelAndUtfasesStatus(FTRL_8_14),
        HjemmelAndUtfasesStatus(FTRL_8_15),
        HjemmelAndUtfasesStatus(FTRL_8_16),
        HjemmelAndUtfasesStatus(FTRL_8_17),
        HjemmelAndUtfasesStatus(FTRL_8_18),
        HjemmelAndUtfasesStatus(FTRL_8_19),
        HjemmelAndUtfasesStatus(FTRL_8_20),
        HjemmelAndUtfasesStatus(FTRL_8_21),
        HjemmelAndUtfasesStatus(FTRL_8_22),
        HjemmelAndUtfasesStatus(FTRL_8_23),
        HjemmelAndUtfasesStatus(FTRL_8_24),
        HjemmelAndUtfasesStatus(FTRL_8_25),
        HjemmelAndUtfasesStatus(FTRL_8_26),
        HjemmelAndUtfasesStatus(FTRL_8_27),
        HjemmelAndUtfasesStatus(FTRL_8_28),
        HjemmelAndUtfasesStatus(FTRL_8_29),
        HjemmelAndUtfasesStatus(FTRL_8_30),
        HjemmelAndUtfasesStatus(FTRL_8_31),
        HjemmelAndUtfasesStatus(FTRL_8_32),
        HjemmelAndUtfasesStatus(FTRL_8_33),
        HjemmelAndUtfasesStatus(FTRL_8_34),
        HjemmelAndUtfasesStatus(FTRL_8_35),
        HjemmelAndUtfasesStatus(FTRL_8_36),
        HjemmelAndUtfasesStatus(FTRL_8_37),
        HjemmelAndUtfasesStatus(FTRL_8_38),
        HjemmelAndUtfasesStatus(FTRL_8_39),
        HjemmelAndUtfasesStatus(FTRL_8_40),
        HjemmelAndUtfasesStatus(FTRL_8_41),
        HjemmelAndUtfasesStatus(FTRL_8_42),
        HjemmelAndUtfasesStatus(FTRL_8_43),
        HjemmelAndUtfasesStatus(FTRL_8_44),
        HjemmelAndUtfasesStatus(FTRL_8_45),
        HjemmelAndUtfasesStatus(FTRL_8_46),
        HjemmelAndUtfasesStatus(FTRL_8_47),
        HjemmelAndUtfasesStatus(FTRL_8_48),
        HjemmelAndUtfasesStatus(FTRL_8_49),
        HjemmelAndUtfasesStatus(FTRL_8_50),
        HjemmelAndUtfasesStatus(FTRL_8_51),
        HjemmelAndUtfasesStatus(FTRL_8_52),
        HjemmelAndUtfasesStatus(FTRL_8_53),
        HjemmelAndUtfasesStatus(FTRL_8_54),
        HjemmelAndUtfasesStatus(FTRL_8_55),

        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FTRL_22_3),
        HjemmelAndUtfasesStatus(FTRL_22_7),
        HjemmelAndUtfasesStatus(FTRL_22_10),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(FTRL_22_17A),

        HjemmelAndUtfasesStatus(ANKENEMNDA),
    ),
    Ytelse.SUP_PEN to listOf(
        HjemmelAndUtfasesStatus(SUP_ST_L_3),
        HjemmelAndUtfasesStatus(SUP_ST_L_4),
        HjemmelAndUtfasesStatus(SUP_ST_L_5),
        HjemmelAndUtfasesStatus(SUP_ST_L_6),
        HjemmelAndUtfasesStatus(SUP_ST_L_7),
        HjemmelAndUtfasesStatus(SUP_ST_L_8),
        HjemmelAndUtfasesStatus(SUP_ST_L_9),
        HjemmelAndUtfasesStatus(SUP_ST_L_10),
        HjemmelAndUtfasesStatus(SUP_ST_L_11),
        HjemmelAndUtfasesStatus(SUP_ST_L_12),
        HjemmelAndUtfasesStatus(SUP_ST_L_13),
        HjemmelAndUtfasesStatus(SUP_ST_L_17),
        HjemmelAndUtfasesStatus(SUP_ST_L_18),
        HjemmelAndUtfasesStatus(SUP_ST_L_21),
        HjemmelAndUtfasesStatus(SUP_ST_L_22),

        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FVL_12),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_35),

        HjemmelAndUtfasesStatus(TRRL_9),
        HjemmelAndUtfasesStatus(TRRL_10),
        HjemmelAndUtfasesStatus(TRRL_11),
    ),
    Ytelse.SUP_UFF to listOf(
        HjemmelAndUtfasesStatus(SUP_ST_L_3),
        HjemmelAndUtfasesStatus(SUP_ST_L_4),
        HjemmelAndUtfasesStatus(SUP_ST_L_5),
        HjemmelAndUtfasesStatus(SUP_ST_L_6),
        HjemmelAndUtfasesStatus(SUP_ST_L_7),
        HjemmelAndUtfasesStatus(SUP_ST_L_8),
        HjemmelAndUtfasesStatus(SUP_ST_L_9),
        HjemmelAndUtfasesStatus(SUP_ST_L_10),
        HjemmelAndUtfasesStatus(SUP_ST_L_11),
        HjemmelAndUtfasesStatus(SUP_ST_L_12),
        HjemmelAndUtfasesStatus(SUP_ST_L_13),
        HjemmelAndUtfasesStatus(SUP_ST_L_17),
        HjemmelAndUtfasesStatus(SUP_ST_L_18),
        HjemmelAndUtfasesStatus(SUP_ST_L_21),
        HjemmelAndUtfasesStatus(SUP_ST_L_22),

        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FVL_12),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_35),

        HjemmelAndUtfasesStatus(TRRL_9),
        HjemmelAndUtfasesStatus(TRRL_10),
        HjemmelAndUtfasesStatus(TRRL_11),
    ),
    Ytelse.FOR_ENG to listOf(
        HjemmelAndUtfasesStatus(FTRL_14_2),
        HjemmelAndUtfasesStatus(FTRL_14_17),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),
    Ytelse.FOR_FOR to listOf(
        HjemmelAndUtfasesStatus(FTRL_14_2),
        HjemmelAndUtfasesStatus(FTRL_14_5),
        HjemmelAndUtfasesStatus(FTRL_14_6),
        HjemmelAndUtfasesStatus(FTRL_14_7),
        HjemmelAndUtfasesStatus(FTRL_14_9),
        HjemmelAndUtfasesStatus(FTRL_14_10),
        HjemmelAndUtfasesStatus(FTRL_14_11),
        HjemmelAndUtfasesStatus(FTRL_14_12),
        HjemmelAndUtfasesStatus(FTRL_14_13),
        HjemmelAndUtfasesStatus(FTRL_14_14),
        HjemmelAndUtfasesStatus(FTRL_14_15),
        HjemmelAndUtfasesStatus(FTRL_14_16),
        HjemmelAndUtfasesStatus(FTRL_14_17),
        HjemmelAndUtfasesStatus(FTRL_8_2),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(EOES_883_2004_5),
        HjemmelAndUtfasesStatus(EOES_883_2004_6),
        HjemmelAndUtfasesStatus(FEDREKVOTESAK),
    ),
    Ytelse.FOR_SVA to listOf(
        HjemmelAndUtfasesStatus(FTRL_14_2),
        HjemmelAndUtfasesStatus(FTRL_14_4),
        HjemmelAndUtfasesStatus(FTRL_14_6),
        HjemmelAndUtfasesStatus(FTRL_14_7),
        HjemmelAndUtfasesStatus(FTRL_8_2),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(EOES_883_2004_6),
    ),
    Ytelse.HJE_HJE to listOf(
        HjemmelAndUtfasesStatus(FTRL_10_3),
        HjemmelAndUtfasesStatus(FTRL_10_4),
        HjemmelAndUtfasesStatus(FTRL_10_5),
        HjemmelAndUtfasesStatus(FTRL_10_6),
        HjemmelAndUtfasesStatus(FTRL_10_7A),
        HjemmelAndUtfasesStatus(FTRL_10_7B),
        HjemmelAndUtfasesStatus(FTRL_10_7C),
        HjemmelAndUtfasesStatus(FTRL_10_7D),
        HjemmelAndUtfasesStatus(FTRL_10_7E),
        HjemmelAndUtfasesStatus(FTRL_10_7F),
        HjemmelAndUtfasesStatus(FTRL_10_7G),
        HjemmelAndUtfasesStatus(FTRL_10_7I_B),
        HjemmelAndUtfasesStatus(FTRL_10_7XA),
        HjemmelAndUtfasesStatus(FTRL_10_7XB),
        HjemmelAndUtfasesStatus(FTRL_10_8),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_8),
        HjemmelAndUtfasesStatus(FTRL_21_10),
        HjemmelAndUtfasesStatus(FTRL_21_12),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_14),
        HjemmelAndUtfasesStatus(FTRL_22_17),

        HjemmelAndUtfasesStatus(FS_AKT_26_2A),
        HjemmelAndUtfasesStatus(FS_AKT_26_2B),
        HjemmelAndUtfasesStatus(FS_AKT_26_4),
        HjemmelAndUtfasesStatus(FS_AKT_26_5),

        HjemmelAndUtfasesStatus(FS_HJE_MM_2A),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2B),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2C),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2D),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2E),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2F),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2G),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2H),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2I),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2J),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2K),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2L),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2M),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2N),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2O),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2P),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2Q),
        HjemmelAndUtfasesStatus(FS_HJE_MM_2R),
        HjemmelAndUtfasesStatus(FS_HJE_MM_4),
        HjemmelAndUtfasesStatus(FS_HJE_MM_6A),
        HjemmelAndUtfasesStatus(FS_HJE_MM_6D),
        HjemmelAndUtfasesStatus(FS_HJE_MM_7),

        HjemmelAndUtfasesStatus(FS_HA_MM_2A),
        HjemmelAndUtfasesStatus(FS_HA_MM_3A),
        HjemmelAndUtfasesStatus(FS_HA_MM_4A),
        HjemmelAndUtfasesStatus(FS_HA_MM_6A),
        HjemmelAndUtfasesStatus(FS_HA_MM_8A),

        HjemmelAndUtfasesStatus(FS_SH_2),

        HjemmelAndUtfasesStatus(EOES_883_2004_11),
        HjemmelAndUtfasesStatus(EOES_883_2004_12),
        HjemmelAndUtfasesStatus(EOES_883_2004_13),
        HjemmelAndUtfasesStatus(EOES_883_2004_23),
        HjemmelAndUtfasesStatus(EOES_883_2004_24),
        HjemmelAndUtfasesStatus(EOES_883_2004_25),
        HjemmelAndUtfasesStatus(EOES_883_2004_33),
        HjemmelAndUtfasesStatus(EOES_883_2004_81),

        HjemmelAndUtfasesStatus(GJ_F_FORD_987_2009_11),

        HjemmelAndUtfasesStatus(NORDISK_KONVENSJON),

        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_12),
        HjemmelAndUtfasesStatus(FVL_14),
        HjemmelAndUtfasesStatus(FVL_16),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_24),
        HjemmelAndUtfasesStatus(FVL_25),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(TRRL_2),
        HjemmelAndUtfasesStatus(TRRL_9),
        HjemmelAndUtfasesStatus(TRRL_10),
        HjemmelAndUtfasesStatus(TRRL_11),
        HjemmelAndUtfasesStatus(TRRL_12),
        HjemmelAndUtfasesStatus(TRRL_14),
    ),
    Ytelse.HJE_AUR to listOf(
        HjemmelAndUtfasesStatus(FS_ARB_UTD_R_2),
        HjemmelAndUtfasesStatus(FS_ARB_UTD_R_3),
        HjemmelAndUtfasesStatus(FS_ARB_UTD_R_4),
        HjemmelAndUtfasesStatus(FS_ARB_UTD_R_5),
        HjemmelAndUtfasesStatus(FS_ARB_UTD_R_6),
        HjemmelAndUtfasesStatus(FS_ARB_UTD_R_8),
        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_12),
        HjemmelAndUtfasesStatus(FVL_14),
        HjemmelAndUtfasesStatus(FVL_16),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_24),
        HjemmelAndUtfasesStatus(FVL_25),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),
    ),
    Ytelse.BIL_BIL to listOf(
        HjemmelAndUtfasesStatus(FTRL_10_3),
        HjemmelAndUtfasesStatus(FTRL_10_4),
        HjemmelAndUtfasesStatus(FTRL_10_5),
        HjemmelAndUtfasesStatus(FTRL_10_6),
        HjemmelAndUtfasesStatus(FTRL_10_7H),
        HjemmelAndUtfasesStatus(FTRL_10_8),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_8),
        HjemmelAndUtfasesStatus(FTRL_21_10),
        HjemmelAndUtfasesStatus(FTRL_21_12),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_14),
        HjemmelAndUtfasesStatus(FTRL_22_17),

        HjemmelAndUtfasesStatus(FS_MOK_2B),
        HjemmelAndUtfasesStatus(FS_MOK_2C),
        HjemmelAndUtfasesStatus(FS_MOK_2D),
        HjemmelAndUtfasesStatus(FS_MOK_3A),
        HjemmelAndUtfasesStatus(FS_MOK_5A),
        HjemmelAndUtfasesStatus(FS_MOK_6A),
        HjemmelAndUtfasesStatus(FS_MOK_7A),
        HjemmelAndUtfasesStatus(FS_MOK_8A),
        HjemmelAndUtfasesStatus(FS_MOK_9A),
        HjemmelAndUtfasesStatus(FS_MOK_11A),
        HjemmelAndUtfasesStatus(FS_MOK_11B),
        HjemmelAndUtfasesStatus(FS_MOK_12A),
        HjemmelAndUtfasesStatus(FS_MOK_13),
        HjemmelAndUtfasesStatus(FS_MOK_14),
        HjemmelAndUtfasesStatus(FS_MOK_15),

        HjemmelAndUtfasesStatus(EOES_883_2004_11),
        HjemmelAndUtfasesStatus(EOES_883_2004_12),
        HjemmelAndUtfasesStatus(EOES_883_2004_13),
        HjemmelAndUtfasesStatus(EOES_883_2004_23),
        HjemmelAndUtfasesStatus(EOES_883_2004_24),
        HjemmelAndUtfasesStatus(EOES_883_2004_25),
        HjemmelAndUtfasesStatus(EOES_883_2004_33),
        HjemmelAndUtfasesStatus(EOES_883_2004_81),

        HjemmelAndUtfasesStatus(GJ_F_FORD_987_2009_11),

        HjemmelAndUtfasesStatus(NORDISK_KONVENSJON),

        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_12),
        HjemmelAndUtfasesStatus(FVL_14),
        HjemmelAndUtfasesStatus(FVL_16),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_24),
        HjemmelAndUtfasesStatus(FVL_25),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(TRRL_2),
        HjemmelAndUtfasesStatus(TRRL_9),
        HjemmelAndUtfasesStatus(TRRL_10),
        HjemmelAndUtfasesStatus(TRRL_11),
        HjemmelAndUtfasesStatus(TRRL_12),
        HjemmelAndUtfasesStatus(TRRL_14),
    ),
    Ytelse.HEL_HEL to listOf(
        HjemmelAndUtfasesStatus(FTRL_10_3),
        HjemmelAndUtfasesStatus(FTRL_10_4),
        HjemmelAndUtfasesStatus(FTRL_10_5),
        HjemmelAndUtfasesStatus(FTRL_10_6),
        HjemmelAndUtfasesStatus(FTRL_10_7I),
        HjemmelAndUtfasesStatus(FTRL_10_8),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_8),
        HjemmelAndUtfasesStatus(FTRL_21_10),
        HjemmelAndUtfasesStatus(FTRL_21_12),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_14),
        HjemmelAndUtfasesStatus(FTRL_22_17),

        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_1A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_1B),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_1C),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_2F),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_3A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_4A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_5A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_6A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_7A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_8G),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_9A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_9AA),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_10A),
        HjemmelAndUtfasesStatus(FS_ORT_HJE_MM_12A),

        HjemmelAndUtfasesStatus(EOES_883_2004_11),
        HjemmelAndUtfasesStatus(EOES_883_2004_12),
        HjemmelAndUtfasesStatus(EOES_883_2004_13),
        HjemmelAndUtfasesStatus(EOES_883_2004_23),
        HjemmelAndUtfasesStatus(EOES_883_2004_24),
        HjemmelAndUtfasesStatus(EOES_883_2004_25),
        HjemmelAndUtfasesStatus(EOES_883_2004_33),
        HjemmelAndUtfasesStatus(EOES_883_2004_81),

        HjemmelAndUtfasesStatus(GJ_F_FORD_987_2009_11),

        HjemmelAndUtfasesStatus(NORDISK_KONVENSJON),

        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_12),
        HjemmelAndUtfasesStatus(FVL_14),
        HjemmelAndUtfasesStatus(FVL_16),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_24),
        HjemmelAndUtfasesStatus(FVL_25),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(TRRL_2),
        HjemmelAndUtfasesStatus(TRRL_9),
        HjemmelAndUtfasesStatus(TRRL_10),
        HjemmelAndUtfasesStatus(TRRL_11),
        HjemmelAndUtfasesStatus(TRRL_12),
        HjemmelAndUtfasesStatus(TRRL_14),
    ),

    Ytelse.PEN_AFP to listOf(
        HjemmelAndUtfasesStatus(AFP_PRIVAT),
        HjemmelAndUtfasesStatus(AFP_62_OFFENTLIG_ETTEROPPGJOER),
        HjemmelAndUtfasesStatus(AFP_62_OFFENTLIG_ANNET),
    ),

    Ytelse.PEN_BAR to listOf(
        HjemmelAndUtfasesStatus(FTRL_18_2),
        HjemmelAndUtfasesStatus(FTRL_18_3),
        HjemmelAndUtfasesStatus(FTRL_18_4),
        HjemmelAndUtfasesStatus(FTRL_18_5),
        HjemmelAndUtfasesStatus(FTRL_18_6),
        HjemmelAndUtfasesStatus(FTRL_18_7),
        HjemmelAndUtfasesStatus(FTRL_18_8),
        HjemmelAndUtfasesStatus(FTRL_18_9),
        HjemmelAndUtfasesStatus(FTRL_18_10),
        HjemmelAndUtfasesStatus(FTRL_18_11_YRKESSKADE_GAMMEL),

        HjemmelAndUtfasesStatus(FTRL_2_1),
        HjemmelAndUtfasesStatus(FTRL_2_2),
        HjemmelAndUtfasesStatus(FTRL_2_5),
        HjemmelAndUtfasesStatus(FTRL_2_13),
        HjemmelAndUtfasesStatus(FTRL_2_14),

        HjemmelAndUtfasesStatus(FTRL_3_3),
        HjemmelAndUtfasesStatus(FTRL_3_5_TRYGDETID),
        HjemmelAndUtfasesStatus(FTRL_3_7),
        HjemmelAndUtfasesStatus(FTRL_3_23),

        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_6),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_10),
        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FTRL_22_7),
        HjemmelAndUtfasesStatus(FTRL_22_8),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_14),
        HjemmelAndUtfasesStatus(FTRL_22_15_1_1),
        HjemmelAndUtfasesStatus(FTRL_22_15_1_2),
        HjemmelAndUtfasesStatus(FTRL_22_15_2),
        HjemmelAndUtfasesStatus(FTRL_22_15_4),
        HjemmelAndUtfasesStatus(FTRL_22_15_5),
        HjemmelAndUtfasesStatus(FTRL_22_15_6),
        HjemmelAndUtfasesStatus(FTRL_22_16),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(FTRL_22_17A),

        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_36),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),

        HjemmelAndUtfasesStatus(EOES_AVTALEN_BEREGNING),

        HjemmelAndUtfasesStatus(EOES_AVTALEN_MEDLEMSKAP_TRYGDETID),
    ),

    Ytelse.PEN_EYO to listOf(
        HjemmelAndUtfasesStatus(FTRL_17_2),
        HjemmelAndUtfasesStatus(FTRL_17_3),
        HjemmelAndUtfasesStatus(FTRL_17_4_1),
        HjemmelAndUtfasesStatus(FTRL_17_4_2),
        HjemmelAndUtfasesStatus(FTRL_17_5_1),
        HjemmelAndUtfasesStatus(FTRL_17_5_2),
        HjemmelAndUtfasesStatus(FTRL_17_5_3),
        HjemmelAndUtfasesStatus(FTRL_17_6_NY),
        HjemmelAndUtfasesStatus(FTRL_17_7_NY),
        HjemmelAndUtfasesStatus(FTRL_17_8_NY),
        HjemmelAndUtfasesStatus(FTRL_17_9_NY),
        HjemmelAndUtfasesStatus(FTRL_17_10),
        HjemmelAndUtfasesStatus(FTRL_17_11),
        HjemmelAndUtfasesStatus(FTRL_17_12),
        HjemmelAndUtfasesStatus(FTRL_17_14),
        HjemmelAndUtfasesStatus(FTRL_17_15),

        HjemmelAndUtfasesStatus(FTRL_1_5),

        HjemmelAndUtfasesStatus(FTRL_2_1),
        HjemmelAndUtfasesStatus(FTRL_2_2),
        HjemmelAndUtfasesStatus(FTRL_2_5),
        HjemmelAndUtfasesStatus(FTRL_2_13),
        HjemmelAndUtfasesStatus(FTRL_2_14),

        HjemmelAndUtfasesStatus(FTRL_3_3),
        HjemmelAndUtfasesStatus(FTRL_3_5_TRYGDETID),
        HjemmelAndUtfasesStatus(FTRL_3_7),
        HjemmelAndUtfasesStatus(FTRL_3_8),
        HjemmelAndUtfasesStatus(FTRL_3_9),
        HjemmelAndUtfasesStatus(FTRL_3_10),
        HjemmelAndUtfasesStatus(FTRL_3_11),
        HjemmelAndUtfasesStatus(FTRL_3_12),
        HjemmelAndUtfasesStatus(FTRL_3_13),
        HjemmelAndUtfasesStatus(FTRL_3_14),
        HjemmelAndUtfasesStatus(FTRL_3_15),
        HjemmelAndUtfasesStatus(FTRL_3_16),
        HjemmelAndUtfasesStatus(FTRL_3_17),
        HjemmelAndUtfasesStatus(FTRL_3_18),
        HjemmelAndUtfasesStatus(FTRL_3_19),
        HjemmelAndUtfasesStatus(FTRL_3_22),
        HjemmelAndUtfasesStatus(FTRL_3_23),

        HjemmelAndUtfasesStatus(FTRL_17_A_1),
        HjemmelAndUtfasesStatus(FTRL_17_A_2),
        HjemmelAndUtfasesStatus(FTRL_17_A_3),
        HjemmelAndUtfasesStatus(FTRL_17_A_4),
        HjemmelAndUtfasesStatus(FTRL_17_A_5),
        HjemmelAndUtfasesStatus(FTRL_17_A_6),
        HjemmelAndUtfasesStatus(FTRL_17_A_7),
        HjemmelAndUtfasesStatus(FTRL_17_A_8),

        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_4),
        HjemmelAndUtfasesStatus(FTRL_21_6),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_10),
        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FTRL_22_7),
        HjemmelAndUtfasesStatus(FTRL_22_8),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_14),
        HjemmelAndUtfasesStatus(FTRL_22_15_1_1),
        HjemmelAndUtfasesStatus(FTRL_22_15_1_2),
        HjemmelAndUtfasesStatus(FTRL_22_15_2),
        HjemmelAndUtfasesStatus(FTRL_22_15_4),
        HjemmelAndUtfasesStatus(FTRL_22_15_5),
        HjemmelAndUtfasesStatus(FTRL_22_15_6),
        HjemmelAndUtfasesStatus(FTRL_22_16),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(FTRL_22_17A),

        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_2),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_3),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_4),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_5),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_6),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_7),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_8),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_9),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_10),

        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_36),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),

        HjemmelAndUtfasesStatus(EOES_AVTALEN_BEREGNING),

        HjemmelAndUtfasesStatus(EOES_AVTALEN_MEDLEMSKAP_TRYGDETID),
    ),

    Ytelse.PEN_GJE to listOf(
        HjemmelAndUtfasesStatus(FTRL_17_2),
        HjemmelAndUtfasesStatus(FTRL_17_2_FOER_2024),
        HjemmelAndUtfasesStatus(FTRL_17_3),
        HjemmelAndUtfasesStatus(FTRL_17_4_1),
        HjemmelAndUtfasesStatus(FTRL_17_4_2),
        HjemmelAndUtfasesStatus(FTRL_17_4),
        HjemmelAndUtfasesStatus(FTRL_17_5_1),
        HjemmelAndUtfasesStatus(FTRL_17_5_2),
        HjemmelAndUtfasesStatus(FTRL_17_5_3),
        HjemmelAndUtfasesStatus(FTRL_17_5),
        HjemmelAndUtfasesStatus(FTRL_17_6_NY),
        HjemmelAndUtfasesStatus(FTRL_17_6),
        HjemmelAndUtfasesStatus(FTRL_17_7_NY),
        HjemmelAndUtfasesStatus(FTRL_17_7),
        HjemmelAndUtfasesStatus(FTRL_17_8_NY),
        HjemmelAndUtfasesStatus(FTRL_17_8),
        HjemmelAndUtfasesStatus(FTRL_17_9_NY),
        HjemmelAndUtfasesStatus(FTRL_17_9),
        HjemmelAndUtfasesStatus(FTRL_17_10),
        HjemmelAndUtfasesStatus(FTRL_17_11),
        HjemmelAndUtfasesStatus(FTRL_17_12),
        HjemmelAndUtfasesStatus(FTRL_17_14),
        HjemmelAndUtfasesStatus(FTRL_17_15),

        HjemmelAndUtfasesStatus(FTRL_1_5),

        HjemmelAndUtfasesStatus(FTRL_2_1),
        HjemmelAndUtfasesStatus(FTRL_2_2),
        HjemmelAndUtfasesStatus(FTRL_2_5),
        HjemmelAndUtfasesStatus(FTRL_2_13),
        HjemmelAndUtfasesStatus(FTRL_2_14),

        HjemmelAndUtfasesStatus(FTRL_3_3),
        HjemmelAndUtfasesStatus(FTRL_3_5_TRYGDETID),
        HjemmelAndUtfasesStatus(FTRL_3_7),
        HjemmelAndUtfasesStatus(FTRL_3_8),
        HjemmelAndUtfasesStatus(FTRL_3_9),
        HjemmelAndUtfasesStatus(FTRL_3_10),
        HjemmelAndUtfasesStatus(FTRL_3_11),
        HjemmelAndUtfasesStatus(FTRL_3_12),
        HjemmelAndUtfasesStatus(FTRL_3_13),
        HjemmelAndUtfasesStatus(FTRL_3_14),
        HjemmelAndUtfasesStatus(FTRL_3_15),
        HjemmelAndUtfasesStatus(FTRL_3_16),
        HjemmelAndUtfasesStatus(FTRL_3_17),
        HjemmelAndUtfasesStatus(FTRL_3_18),
        HjemmelAndUtfasesStatus(FTRL_3_19),
        HjemmelAndUtfasesStatus(FTRL_3_22),
        HjemmelAndUtfasesStatus(FTRL_3_23),

        HjemmelAndUtfasesStatus(FTRL_17_A_1),
        HjemmelAndUtfasesStatus(FTRL_17_A_2),
        HjemmelAndUtfasesStatus(FTRL_17_A_3),
        HjemmelAndUtfasesStatus(FTRL_17_A_4),
        HjemmelAndUtfasesStatus(FTRL_17_A_5),
        HjemmelAndUtfasesStatus(FTRL_17_A_6),
        HjemmelAndUtfasesStatus(FTRL_17_A_7),
        HjemmelAndUtfasesStatus(FTRL_17_A_8),

        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_4),
        HjemmelAndUtfasesStatus(FTRL_21_6),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_10),
        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FTRL_22_7),
        HjemmelAndUtfasesStatus(FTRL_22_8),
        HjemmelAndUtfasesStatus(FTRL_22_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_14),
        HjemmelAndUtfasesStatus(FTRL_22_15_1_1),
        HjemmelAndUtfasesStatus(FTRL_22_15_1_2),
        HjemmelAndUtfasesStatus(FTRL_22_15_2),
        HjemmelAndUtfasesStatus(FTRL_22_15_4),
        HjemmelAndUtfasesStatus(FTRL_22_15_5),
        HjemmelAndUtfasesStatus(FTRL_22_15_6),
        HjemmelAndUtfasesStatus(FTRL_22_16),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(FTRL_22_17A),

        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_2),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_3),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_4),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_5),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_6),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_7),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_8),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_9),
        HjemmelAndUtfasesStatus(FS_YTELSE_TIL_GJENLEVENDE_EKTEFELLE_OG_TIDLIGERE_FAMILIEPLEIER_10),

        HjemmelAndUtfasesStatus(FVL_21),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_33),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_36),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),

        HjemmelAndUtfasesStatus(EOES_AVTALEN_BEREGNING),

        HjemmelAndUtfasesStatus(EOES_AVTALEN_MEDLEMSKAP_TRYGDETID),
    ),
    Ytelse.GRU_HJE to hjemlerGRU,
    Ytelse.GRU_GRU to hjemlerGRU,

    Ytelse.YRK_MEN to hjemlerYRK,
    Ytelse.YRK_YRK to hjemlerYRK,
    Ytelse.YRK_YSY to hjemlerYRK,

    Ytelse.MED_MED to listOf(
        HjemmelAndUtfasesStatus(FTRL_2_1),
        HjemmelAndUtfasesStatus(FTRL_2_2),
        HjemmelAndUtfasesStatus(FTRL_2_3),
        HjemmelAndUtfasesStatus(FTRL_2_4),
        HjemmelAndUtfasesStatus(FTRL_2_5),
        HjemmelAndUtfasesStatus(FTRL_2_6),
        HjemmelAndUtfasesStatus(FTRL_2_7),
        HjemmelAndUtfasesStatus(FTRL_2_8),
        HjemmelAndUtfasesStatus(FTRL_2_11),
        HjemmelAndUtfasesStatus(FTRL_2_12),
        HjemmelAndUtfasesStatus(FTRL_2_13),
        HjemmelAndUtfasesStatus(FTRL_2_14),
        HjemmelAndUtfasesStatus(FTRL_2_15),
        HjemmelAndUtfasesStatus(FTRL_2_17),
        HjemmelAndUtfasesStatus(FTRL_21_12),
        HjemmelAndUtfasesStatus(FTRL_23_3),

        HjemmelAndUtfasesStatus(TRRL_9),

        HjemmelAndUtfasesStatus(EOES_883_2004),
        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),
    ),

    Ytelse.GRA_GRA to listOf(
        HjemmelAndUtfasesStatus(FTRL_7_2),
        HjemmelAndUtfasesStatus(FTRL_7_3),
        HjemmelAndUtfasesStatus(FTRL_22_13_2),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),

    Ytelse.FOS_FOS to listOf(
        HjemmelAndUtfasesStatus(FTRL_8_36),
        HjemmelAndUtfasesStatus(FTRL_8_37),
        HjemmelAndUtfasesStatus(FTRL_8_39),
    ),

    Ytelse.PEN_ALD to listOf(
        HjemmelAndUtfasesStatus(FTRL_19_OG_20_UFOERE_TIL_ALDER),
        HjemmelAndUtfasesStatus(FTRL_19_OG_20_BEREGNING),
        HjemmelAndUtfasesStatus(FTRL_19_2),
        HjemmelAndUtfasesStatus(FTRL_19_3),
        HjemmelAndUtfasesStatus(FTRL_19_4),
        HjemmelAndUtfasesStatus(FTRL_19_5),
        HjemmelAndUtfasesStatus(FTRL_19_5_BEREGNING),
        HjemmelAndUtfasesStatus(FTRL_19_6),
        HjemmelAndUtfasesStatus(FTRL_19_7),
        HjemmelAndUtfasesStatus(FTRL_19_8_MINSTE_PENSJONSNIVAA),
        HjemmelAndUtfasesStatus(FTRL_19_9),
        HjemmelAndUtfasesStatus(FTRL_19_10),
        HjemmelAndUtfasesStatus(FTRL_19_11_OG_20_15),
        HjemmelAndUtfasesStatus(FTRL_19_12),
        HjemmelAndUtfasesStatus(FTRL_19_13_OG_20_17),
        HjemmelAndUtfasesStatus(FTRL_19_14),
        HjemmelAndUtfasesStatus(FTRL_19_15),
        HjemmelAndUtfasesStatus(FTRL_19_16_GJENLEVENDETILLEGG),
        HjemmelAndUtfasesStatus(FTRL_19_17),
        HjemmelAndUtfasesStatus(FTRL_19_18),
        HjemmelAndUtfasesStatus(FTRL_19_19),
        HjemmelAndUtfasesStatus(FTRL_19_20_YRKESSKADE),
        HjemmelAndUtfasesStatus(FTRL_19_21_INSTITUSJON),
        HjemmelAndUtfasesStatus(FTRL_19_22_SONING),

        HjemmelAndUtfasesStatus(FTRL_1_5),

        HjemmelAndUtfasesStatus(FTRL_2_1_2_2_2_4_2_13_2_14_MEDLEMSKAP),

        HjemmelAndUtfasesStatus(FTRL_3_2_INNTEKT),
        HjemmelAndUtfasesStatus(FTRL_3_2_SIVILSTAND),
        HjemmelAndUtfasesStatus(FTRL_3_3),
        HjemmelAndUtfasesStatus(FTRL_3_5_TRYGDETID),
        HjemmelAndUtfasesStatus(FTRL_3_7),
        HjemmelAndUtfasesStatus(FTRL_3_8),
        HjemmelAndUtfasesStatus(FTRL_3_9),
        HjemmelAndUtfasesStatus(FTRL_3_10),
        HjemmelAndUtfasesStatus(FTRL_3_11),
        HjemmelAndUtfasesStatus(FTRL_3_12),
        HjemmelAndUtfasesStatus(FTRL_3_13),
        HjemmelAndUtfasesStatus(FTRL_3_14_PP),
        HjemmelAndUtfasesStatus(FTRL_3_15_PI),
        HjemmelAndUtfasesStatus(FTRL_3_16_OMSORGSPOENG),
        HjemmelAndUtfasesStatus(FTRL_3_17),
        HjemmelAndUtfasesStatus(FTRL_3_18),
        HjemmelAndUtfasesStatus(FTRL_3_19),
        HjemmelAndUtfasesStatus(FTRL_3_22),
        HjemmelAndUtfasesStatus(FTRL_3_23),
        HjemmelAndUtfasesStatus(FTRL_3_24_3_26_EKTEFELLETILLEGG),
        HjemmelAndUtfasesStatus(FTRL_3_25_3_26_BARNETILLEGG),

        HjemmelAndUtfasesStatus(FTRL_20_2),
        HjemmelAndUtfasesStatus(FTRL_20_3),
        HjemmelAndUtfasesStatus(FTRL_20_4),
        HjemmelAndUtfasesStatus(FTRL_20_5),
        HjemmelAndUtfasesStatus(FTRL_20_6),
        HjemmelAndUtfasesStatus(FTRL_20_7),
        HjemmelAndUtfasesStatus(FTRL_20_7_A),
        HjemmelAndUtfasesStatus(FTRL_20_8),
        HjemmelAndUtfasesStatus(FTRL_20_9),
        HjemmelAndUtfasesStatus(FTRL_20_10),
        HjemmelAndUtfasesStatus(FTRL_20_11),
        HjemmelAndUtfasesStatus(FTRL_20_12),
        HjemmelAndUtfasesStatus(FTRL_20_13),
        HjemmelAndUtfasesStatus(FTRL_20_14),
        HjemmelAndUtfasesStatus(FTRL_20_14_BEREGNING),
        HjemmelAndUtfasesStatus(FTRL_20_15),
        HjemmelAndUtfasesStatus(FTRL_20_16),
        HjemmelAndUtfasesStatus(FTRL_20_17),
        HjemmelAndUtfasesStatus(FTRL_20_18),
        HjemmelAndUtfasesStatus(FTRL_20_19),
        HjemmelAndUtfasesStatus(FTRL_20_19_A),
        HjemmelAndUtfasesStatus(FTRL_20_20),
        HjemmelAndUtfasesStatus(FTRL_20_21),
        HjemmelAndUtfasesStatus(FTRL_20_22),
        HjemmelAndUtfasesStatus(FTRL_20_23),

        HjemmelAndUtfasesStatus(FTRL_21_6),
        HjemmelAndUtfasesStatus(FTRL_21_12_KLAGEFRIST),

        HjemmelAndUtfasesStatus(FTRL_22_6),
        HjemmelAndUtfasesStatus(FTRL_22_8),
        HjemmelAndUtfasesStatus(FTRL_22_12_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15_TILBAKEKREVING),
        HjemmelAndUtfasesStatus(FTRL_22_15_TILBAKEKREVING_DOEDSBO),
        HjemmelAndUtfasesStatus(FTRL_22_16),
        HjemmelAndUtfasesStatus(FTRL_22_17),

        HjemmelAndUtfasesStatus(FVL_35_C_UGUNST),

        HjemmelAndUtfasesStatus(EOES_883_2004_1),
        HjemmelAndUtfasesStatus(EOES_883_2004_2_OMFATTET),
        HjemmelAndUtfasesStatus(EOES_883_2004_6_SAMMENLEGGING),
        HjemmelAndUtfasesStatus(EOES_883_2004_7),
        HjemmelAndUtfasesStatus(EOES_883_2004_10),
        HjemmelAndUtfasesStatus(EOES_883_2004_11),
        HjemmelAndUtfasesStatus(EOES_883_2004_12),
        HjemmelAndUtfasesStatus(EOES_883_2004_13_AKTIVITET_I_FLERE_LAND),
        HjemmelAndUtfasesStatus(EOES_883_2004_50),
        HjemmelAndUtfasesStatus(EOES_883_2004_51_SAMMENLEGGING),
        HjemmelAndUtfasesStatus(EOES_883_2004_52),
        HjemmelAndUtfasesStatus(EOES_883_2004_53),
        HjemmelAndUtfasesStatus(EOES_883_2004_54),
        HjemmelAndUtfasesStatus(EOES_883_2004_55),
        HjemmelAndUtfasesStatus(EOES_883_2004_56),
        HjemmelAndUtfasesStatus(EOES_883_2004_57),
        HjemmelAndUtfasesStatus(EOES_883_2004_58_MINSTEYTELSE),
        HjemmelAndUtfasesStatus(EOES_883_2004_59),
        HjemmelAndUtfasesStatus(EOES_883_2004_60),
        HjemmelAndUtfasesStatus(EOES_883_2004_70),
        HjemmelAndUtfasesStatus(EOES_883_2004_87),

        HjemmelAndUtfasesStatus(GJ_F_FORD_987_2009_10),
        HjemmelAndUtfasesStatus(GJ_F_FORD_987_2009_11),
        HjemmelAndUtfasesStatus(GJ_F_FORD_987_2009_12),

        HjemmelAndUtfasesStatus(ANDRE_TRYGDEAVTALER),
        HjemmelAndUtfasesStatus(TRYGDEAVTALE_MED_ENGLAND),
        HjemmelAndUtfasesStatus(TRYGDEAVTALE_MED_USA),
        HjemmelAndUtfasesStatus(NORDISK_KONVENSJON),
    ),

    Ytelse.UFO_UFO to listOf(
        HjemmelAndUtfasesStatus(FTRL_12_2),
        HjemmelAndUtfasesStatus(FTRL_12_2_12_8),
        HjemmelAndUtfasesStatus(FTRL_12_2_6_57),
        HjemmelAndUtfasesStatus(FTRL_12_2_TRYGDEAVTALE),
        HjemmelAndUtfasesStatus(FTRL_12_3),
        HjemmelAndUtfasesStatus(FTRL_12_3_EOES),
        HjemmelAndUtfasesStatus(FTRL_12_3_TRYGDEAVTALE),
        HjemmelAndUtfasesStatus(FTRL_12_5),
        HjemmelAndUtfasesStatus(FTRL_12_6),
        HjemmelAndUtfasesStatus(FTRL_12_7_12_9_12_10),
        HjemmelAndUtfasesStatus(FTRL_12_8),
        HjemmelAndUtfasesStatus(FTRL_12_8_UNG_UFOER),
        HjemmelAndUtfasesStatus(FTRL_12_11_12_12_12_13_BEREGNING),
        HjemmelAndUtfasesStatus(FTRL_12_11_12_12_12_13_ART_52),
        HjemmelAndUtfasesStatus(FTRL_12_11_12_12_12_13_TRYGDEAVTALE),
        HjemmelAndUtfasesStatus(FTRL_12_13_SIVILSTAND),
        HjemmelAndUtfasesStatus(FTRL_12_13_UNG_UFOER),
        HjemmelAndUtfasesStatus(FTRL_12_14_EO),
        HjemmelAndUtfasesStatus(FTRL_12_14_EO_ARBEIDSFORSOEK),
        HjemmelAndUtfasesStatus(FTRL_12_14_INNTEKTSENDRING),
        HjemmelAndUtfasesStatus(FTRL_12_15),
        HjemmelAndUtfasesStatus(FTRL_12_16),
        HjemmelAndUtfasesStatus(FTRL_12_17),
        HjemmelAndUtfasesStatus(FTRL_12_19),
        HjemmelAndUtfasesStatus(FTRL_12_20),

        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FTRL_22_12_FVL_35_C),
        HjemmelAndUtfasesStatus(FTRL_22_12_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17),

        HjemmelAndUtfasesStatus(FVL_35_C_UGUNST),
    ),

    Ytelse.TSR_ASO to listOf(
        HjemmelAndUtfasesStatus(ARBML_13),
        HjemmelAndUtfasesStatus(ARBML_17),
        HjemmelAndUtfasesStatus(ARBML_22),
        HjemmelAndUtfasesStatus(FS_TILL_ST_1_3_MOBILITET),
        HjemmelAndUtfasesStatus(FS_TILL_ST_3_REISE),
        HjemmelAndUtfasesStatus(FS_TILL_ST_5),
        HjemmelAndUtfasesStatus(FS_TILL_ST_6_FLYTTING),
        HjemmelAndUtfasesStatus(FS_TILL_ST_15_2),
        HjemmelAndUtfasesStatus(FS_TILL_ST_15_3),
        HjemmelAndUtfasesStatus(FL_2_3),
        HjemmelAndUtfasesStatus(FL_10),
        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),
    ),

    Ytelse.TSO_TSO to listOf(
        HjemmelAndUtfasesStatus(ARBML_13),
        HjemmelAndUtfasesStatus(ARBML_17),
        HjemmelAndUtfasesStatus(ARBML_22),

        HjemmelAndUtfasesStatus(FTRL_11_A_3),
        HjemmelAndUtfasesStatus(FTRL_11_A_4),
        HjemmelAndUtfasesStatus(FTRL_11_A_4_3),

        HjemmelAndUtfasesStatus(FTRL_15_11),

        HjemmelAndUtfasesStatus(FTRL_17_10),
        HjemmelAndUtfasesStatus(FTRL_17_15),

        HjemmelAndUtfasesStatus(FTRL_21_12),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17A),

        HjemmelAndUtfasesStatus(FS_TILL_ST_1_3_MOBILITET),
        HjemmelAndUtfasesStatus(FS_TILL_ST_3_REISE),
        HjemmelAndUtfasesStatus(FS_TILL_ST_6_FLYTTING),
        HjemmelAndUtfasesStatus(FS_TILL_ST_8_BOLIG),
        HjemmelAndUtfasesStatus(FS_TILL_ST_10_TILSYN),
        HjemmelAndUtfasesStatus(FS_TILL_ST_12_LAEREMIDLER),
        HjemmelAndUtfasesStatus(FS_TILL_ST_15_2),
        HjemmelAndUtfasesStatus(FS_TILL_ST_15_3),

        HjemmelAndUtfasesStatus(FL_2_3),
        HjemmelAndUtfasesStatus(FL_10),

        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),
    ),

    Ytelse.AAP_AAP to listOf(
        HjemmelAndUtfasesStatus(FTRL_KAPITTEL_2),
        HjemmelAndUtfasesStatus(FTRL_21_12_FVL_31),
        HjemmelAndUtfasesStatus(EOES_883_2004),
        HjemmelAndUtfasesStatus(FTRL_11_2),
        HjemmelAndUtfasesStatus(FTRL_11_3),
        HjemmelAndUtfasesStatus(FTRL_11_4),
        HjemmelAndUtfasesStatus(FTRL_11_5),
        HjemmelAndUtfasesStatus(FTRL_11_6),
        HjemmelAndUtfasesStatus(FTRL_11_7_11_8_11_9),
        HjemmelAndUtfasesStatus(FTRL_11_10),
        HjemmelAndUtfasesStatus(FTRL_11_12),
        HjemmelAndUtfasesStatus(FTRL_11_13),
        HjemmelAndUtfasesStatus(FTRL_11_14),
        HjemmelAndUtfasesStatus(FTRL_11_15),
        HjemmelAndUtfasesStatus(FTRL_11_17),
        HjemmelAndUtfasesStatus(FTRL_11_18),
        HjemmelAndUtfasesStatus(FTRL_11_19_11_20),
        HjemmelAndUtfasesStatus(FTRL_11_22),
        HjemmelAndUtfasesStatus(FTRL_11_23),
        HjemmelAndUtfasesStatus(FTRL_11_24),
        HjemmelAndUtfasesStatus(FTRL_11_25),
        HjemmelAndUtfasesStatus(FTRL_11_26),
        HjemmelAndUtfasesStatus(FTRL_11_27_11_28),
        HjemmelAndUtfasesStatus(FTRL_11_29),
        HjemmelAndUtfasesStatus(FTRL_11_31),
        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(TRRL_9_FVL_31),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(TRRL_27),
    ),

    Ytelse.DAG_DAG to listOf(
        HjemmelAndUtfasesStatus(FTRL_4_2),
        HjemmelAndUtfasesStatus(FTRL_4_3_1),
        HjemmelAndUtfasesStatus(FTRL_4_3_1_PERMLL),
        HjemmelAndUtfasesStatus(FTRL_4_3_2),
        HjemmelAndUtfasesStatus(FTRL_4_4),
        HjemmelAndUtfasesStatus(FTRL_4_5_REGISTRERING),
        HjemmelAndUtfasesStatus(FTRL_4_5_REELL_ARBEIDSSOEKER),
        HjemmelAndUtfasesStatus(FTRL_4_6_UTDANNING),
        HjemmelAndUtfasesStatus(FTRL_4_6_ETABLERING),
        HjemmelAndUtfasesStatus(FTRL_4_7_PERMITTERINGSAARSAK),
        HjemmelAndUtfasesStatus(FTRL_4_7_PERMITTERINGENS_LENGDE),
        HjemmelAndUtfasesStatus(FTRL_4_8),
        HjemmelAndUtfasesStatus(FTRL_4_9),
        HjemmelAndUtfasesStatus(FTRL_4_10),
        HjemmelAndUtfasesStatus(FTRL_4_11),
        HjemmelAndUtfasesStatus(FTRL_4_12),
        HjemmelAndUtfasesStatus(FTRL_4_13),
        HjemmelAndUtfasesStatus(FTRL_4_14),
        HjemmelAndUtfasesStatus(FTRL_4_15),
        HjemmelAndUtfasesStatus(FTRL_4_16),
        HjemmelAndUtfasesStatus(FTRL_4_18),
        HjemmelAndUtfasesStatus(FTRL_4_19),
        HjemmelAndUtfasesStatus(FTRL_4_20),
        HjemmelAndUtfasesStatus(FTRL_4_22),
        HjemmelAndUtfasesStatus(FTRL_4_23),
        HjemmelAndUtfasesStatus(FTRL_4_24),
        HjemmelAndUtfasesStatus(FTRL_4_25),
        HjemmelAndUtfasesStatus(FTRL_4_26),
        HjemmelAndUtfasesStatus(FTRL_4_27),
        HjemmelAndUtfasesStatus(FTRL_4_28),

        HjemmelAndUtfasesStatus(FTRL_21_3),
        HjemmelAndUtfasesStatus(FTRL_21_7),
        HjemmelAndUtfasesStatus(FTRL_21_12),

        HjemmelAndUtfasesStatus(FTRL_22_13),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17A),

        HjemmelAndUtfasesStatus(FS_DAG_2_1_FORSKUTTERTE_DAGPENGER),
        HjemmelAndUtfasesStatus(FS_DAG_3A_1),
        HjemmelAndUtfasesStatus(FS_DAG_6_7_FISKEPERMITTERING),

        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(EOES_883_2004_61),
        HjemmelAndUtfasesStatus(EOES_883_2004_64),
        HjemmelAndUtfasesStatus(EOES_883_2004_65_1),
        HjemmelAndUtfasesStatus(EOES_883_2004_65_2),

        HjemmelAndUtfasesStatus(TRRL_9),
        HjemmelAndUtfasesStatus(TRRL_10),
        HjemmelAndUtfasesStatus(TRRL_11),
        HjemmelAndUtfasesStatus(TRRL_14),
        HjemmelAndUtfasesStatus(TRRL_27),
    ),

    Ytelse.UNG_UNG to listOf(
        HjemmelAndUtfasesStatus(FS_UNG_1),
        HjemmelAndUtfasesStatus(FS_UNG_2),
        HjemmelAndUtfasesStatus(FS_UNG_3),
        HjemmelAndUtfasesStatus(FS_UNG_4),
        HjemmelAndUtfasesStatus(FS_UNG_6),
        HjemmelAndUtfasesStatus(FS_UNG_7),
        HjemmelAndUtfasesStatus(FS_UNG_8),
        HjemmelAndUtfasesStatus(FS_UNG_9),
        HjemmelAndUtfasesStatus(FS_UNG_10),
        HjemmelAndUtfasesStatus(FS_UNG_11),
        HjemmelAndUtfasesStatus(FS_UNG_12),
        HjemmelAndUtfasesStatus(FS_UNG_14),
        HjemmelAndUtfasesStatus(ARBML_12),
        HjemmelAndUtfasesStatus(ARBML_13),
        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_29),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_34),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(FTRL_22_17A),
    ),

    Ytelse.PEN_KRI to listOf(
        HjemmelAndUtfasesStatus(LOV_OM_KRIGSPENSJON_FOR_MILITÆRPERSONER),
        HjemmelAndUtfasesStatus(LOV_OM_KRIGSPENSJON_FOR_SIVILE),
        HjemmelAndUtfasesStatus(FTRL_22_15),
    ),

    Ytelse.PEN_GYS to listOf(
        HjemmelAndUtfasesStatus(GAMMEL_YRKESSKADE),
    ),

    Ytelse.TIL_TIP to listOf(
        HjemmelAndUtfasesStatus(ARBML_2),
        HjemmelAndUtfasesStatus(ARBML_13),
        HjemmelAndUtfasesStatus(ARBML_13_LOENN),
        HjemmelAndUtfasesStatus(ARBML_13_4),
        HjemmelAndUtfasesStatus(ARBML_15),
        HjemmelAndUtfasesStatus(ARBML_17),
        HjemmelAndUtfasesStatus(ARBML_22),

        HjemmelAndUtfasesStatus(FS_TIP_2),
        HjemmelAndUtfasesStatus(FS_TIP_3),
        HjemmelAndUtfasesStatus(FS_TIP_5),
        HjemmelAndUtfasesStatus(FS_TIP_6),
        HjemmelAndUtfasesStatus(FS_TIP_7),
        HjemmelAndUtfasesStatus(FS_TIP_8),
        HjemmelAndUtfasesStatus(FS_TIP_9),
        HjemmelAndUtfasesStatus(FS_TIP_10),
        HjemmelAndUtfasesStatus(FS_TIP_11),

        HjemmelAndUtfasesStatus(FVL_11),
        HjemmelAndUtfasesStatus(FVL_17),
        HjemmelAndUtfasesStatus(FVL_18_19),
        HjemmelAndUtfasesStatus(FVL_28),
        HjemmelAndUtfasesStatus(FVL_30),
        HjemmelAndUtfasesStatus(FVL_31),
        HjemmelAndUtfasesStatus(FVL_32),
        HjemmelAndUtfasesStatus(FVL_35),
        HjemmelAndUtfasesStatus(FVL_41),
        HjemmelAndUtfasesStatus(FVL_42),

        HjemmelAndUtfasesStatus(FTRL_22_15),
        HjemmelAndUtfasesStatus(FTRL_22_17),
        HjemmelAndUtfasesStatus(FL_2_3),
        HjemmelAndUtfasesStatus(FL_10),
    )
)