package no.nav.klage.kodeverk.hjemmel

import no.nav.klage.kodeverk.Ytelse

val ytelseTilRegistreringshjemler = mapOf(
    Ytelse.HJE_HJE to listOf(

        Registreringshjemmel.FTRL_10_1,
        Registreringshjemmel.FTRL_10_2,
        Registreringshjemmel.FTRL_10_3,
        Registreringshjemmel.FTRL_10_4,
        Registreringshjemmel.FTRL_10_5,
        Registreringshjemmel.FTRL_10_6,
        Registreringshjemmel.FTRL_10_7,
        Registreringshjemmel.FTRL_10_8,
        Registreringshjemmel.FTRL_10_9,
        Registreringshjemmel.FTRL_10_10,
        Registreringshjemmel.FTRL_10_11,
        Registreringshjemmel.FTRL_10_12,
        Registreringshjemmel.FTRL_10_13,
        Registreringshjemmel.FTRL_10_14,
        Registreringshjemmel.FTRL_10_15,
        Registreringshjemmel.FTRL_10_16,
        Registreringshjemmel.FTRL_10_17,
        Registreringshjemmel.FTRL_10_18,
        Registreringshjemmel.FTRL_10_19,
        Registreringshjemmel.FTRL_10_20,
        Registreringshjemmel.FTRL_10_21,
        Registreringshjemmel.FTRL_10_22,
        Registreringshjemmel.FTRL_10_23,
        Registreringshjemmel.FTRL_10_24,
        Registreringshjemmel.FTRL_10_25,
        Registreringshjemmel.FTRL_10_26,
        Registreringshjemmel.FTRL_10_27,
        Registreringshjemmel.FTRL_10_28,
        Registreringshjemmel.FTRL_10_29,
        Registreringshjemmel.FTRL_10_30,
        Registreringshjemmel.FTRL_10_31,

        Registreringshjemmel.FS_AKT_26_1,
        Registreringshjemmel.FS_AKT_26_2,
        Registreringshjemmel.FS_AKT_26_3,
        Registreringshjemmel.FS_AKT_26_4,
        Registreringshjemmel.FS_AKT_26_5,

        Registreringshjemmel.FS_HJE_MM_1,
        Registreringshjemmel.FS_HJE_MM_2,
        Registreringshjemmel.FS_HJE_MM_3,
        Registreringshjemmel.FS_HJE_MM_4,
        Registreringshjemmel.FS_HJE_MM_5,
        Registreringshjemmel.FS_HJE_MM_6,
        Registreringshjemmel.FS_HJE_MM_7,
        Registreringshjemmel.FS_HJE_MM_8,
        Registreringshjemmel.FS_HJE_MM_9,
        Registreringshjemmel.FS_HJE_MM_10,
        Registreringshjemmel.FS_HJE_MM_11,
        Registreringshjemmel.FS_HJE_MM_12,
        Registreringshjemmel.FS_HJE_MM_13,
        Registreringshjemmel.FS_HJE_MM_14,
        Registreringshjemmel.FS_HJE_MM_15,
        Registreringshjemmel.FS_HJE_MM_16,
        Registreringshjemmel.FS_HJE_MM_17,
        Registreringshjemmel.FS_HJE_MM_18,
        Registreringshjemmel.FS_HJE_MM_19,
        Registreringshjemmel.FS_HJE_MM_20,
        Registreringshjemmel.FS_HJE_MM_21,
        Registreringshjemmel.FS_HJE_MM_22,
        Registreringshjemmel.FS_ORT_HJE_MM_1,
        Registreringshjemmel.FS_ORT_HJE_MM_2,
        Registreringshjemmel.FS_ORT_HJE_MM_3,
        Registreringshjemmel.FS_ORT_HJE_MM_4,
        Registreringshjemmel.FS_ORT_HJE_MM_5,
        Registreringshjemmel.FS_ORT_HJE_MM_6,
        Registreringshjemmel.FS_ORT_HJE_MM_7,
        Registreringshjemmel.FS_ORT_HJE_MM_8,
        Registreringshjemmel.FS_ORT_HJE_MM_9,
        Registreringshjemmel.FS_ORT_HJE_MM_10,
        Registreringshjemmel.FS_ORT_HJE_MM_11,
        Registreringshjemmel.FS_ORT_HJE_MM_12,
        Registreringshjemmel.FS_ORT_HJE_MM_13,
        Registreringshjemmel.FS_ORT_HJE_MM_14,
        Registreringshjemmel.FS_ORT_HJE_MM_15,
        Registreringshjemmel.FS_ORT_HJE_MM_16,
        Registreringshjemmel.FS_ORT_HJE_MM_17,
        Registreringshjemmel.FS_ORT_HJE_MM_18,
        Registreringshjemmel.FS_ORT_HJE_MM_19,
        Registreringshjemmel.FS_ORT_HJE_MM_20,
        Registreringshjemmel.FS_ORT_HJE_MM_21,

        Registreringshjemmel.FS_HA_MM_1,
        Registreringshjemmel.FS_HA_MM_2,
        Registreringshjemmel.FS_HA_MM_3,
        Registreringshjemmel.FS_HA_MM_4,
        Registreringshjemmel.FS_HA_MM_5,
        Registreringshjemmel.FS_HA_MM_6,
        Registreringshjemmel.FS_HA_MM_7,
        Registreringshjemmel.FS_HA_MM_8,
        Registreringshjemmel.FS_HA_MM_9,
        Registreringshjemmel.FS_HA_MM_10,
        Registreringshjemmel.FS_HA_MM_11,
        Registreringshjemmel.FS_HA_MM_12,
        Registreringshjemmel.FS_HA_MM_13,

        Registreringshjemmel.FS_SH_1,

        Registreringshjemmel.FS_MOK_1,
        Registreringshjemmel.FS_MOK_2,
        Registreringshjemmel.FS_MOK_3,
        Registreringshjemmel.FS_MOK_4,
        Registreringshjemmel.FS_MOK_5,
        Registreringshjemmel.FS_MOK_6,
        Registreringshjemmel.FS_MOK_7,
        Registreringshjemmel.FS_MOK_8,
        Registreringshjemmel.FS_MOK_9,
        Registreringshjemmel.FS_MOK_10,
        Registreringshjemmel.FS_MOK_11,
        Registreringshjemmel.FS_MOK_12,
        Registreringshjemmel.FS_MOK_13,
        Registreringshjemmel.FS_MOK_14,

        Registreringshjemmel.FTRL_21_3,
        Registreringshjemmel.FTRL_21_7,
        Registreringshjemmel.FTRL_21_8,
        Registreringshjemmel.FTRL_21_10,
        Registreringshjemmel.FTRL_21_12,
        Registreringshjemmel.FTRL_22_12,
        Registreringshjemmel.FTRL_22_13,
        Registreringshjemmel.FTRL_22_14,
        Registreringshjemmel.FTRL_22_17,

        Registreringshjemmel.FVL_11,
        Registreringshjemmel.FVL_12,
        Registreringshjemmel.FVL_16,
        Registreringshjemmel.FVL_17,
        Registreringshjemmel.FVL_18_19,
        Registreringshjemmel.FVL_21,
        Registreringshjemmel.FVL_24,
        Registreringshjemmel.FVL_25,
        Registreringshjemmel.FVL_28,
        Registreringshjemmel.FVL_29,
        Registreringshjemmel.FVL_30,
        Registreringshjemmel.FVL_31,
        Registreringshjemmel.FVL_32,
        Registreringshjemmel.FVL_33,
        Registreringshjemmel.FVL_35,
        Registreringshjemmel.FVL_41,
        Registreringshjemmel.FVL_42,

        Registreringshjemmel.TRRL_2,
        Registreringshjemmel.TRRL_9,
        Registreringshjemmel.TRRL_10,
        Registreringshjemmel.TRRL_11,
        Registreringshjemmel.TRRL_12,
        Registreringshjemmel.TRRL_14,
    )
)

