package no.nav.klage.kodeverk.hjemmel

import no.nav.klage.kodeverk.Ytelse

val ytelseTilRegistreringsHjemler = mapOf(
    Ytelse.HJE_HJE to listOf(

        RegistreringsHjemmel.FTRL_10_1,
        RegistreringsHjemmel.FTRL_10_2,
        RegistreringsHjemmel.FTRL_10_3,
        RegistreringsHjemmel.FTRL_10_4,
        RegistreringsHjemmel.FTRL_10_5,
        RegistreringsHjemmel.FTRL_10_6,
        RegistreringsHjemmel.FTRL_10_7,
        RegistreringsHjemmel.FTRL_10_8,
        RegistreringsHjemmel.FTRL_10_9,
        RegistreringsHjemmel.FTRL_10_10,
        RegistreringsHjemmel.FTRL_10_11,
        RegistreringsHjemmel.FTRL_10_12,
        RegistreringsHjemmel.FTRL_10_13,
        RegistreringsHjemmel.FTRL_10_14,
        RegistreringsHjemmel.FTRL_10_15,
        RegistreringsHjemmel.FTRL_10_16,
        RegistreringsHjemmel.FTRL_10_17,
        RegistreringsHjemmel.FTRL_10_18,
        RegistreringsHjemmel.FTRL_10_19,
        RegistreringsHjemmel.FTRL_10_20,
        RegistreringsHjemmel.FTRL_10_21,
        RegistreringsHjemmel.FTRL_10_22,
        RegistreringsHjemmel.FTRL_10_23,
        RegistreringsHjemmel.FTRL_10_24,
        RegistreringsHjemmel.FTRL_10_25,
        RegistreringsHjemmel.FTRL_10_26,
        RegistreringsHjemmel.FTRL_10_27,
        RegistreringsHjemmel.FTRL_10_28,
        RegistreringsHjemmel.FTRL_10_29,
        RegistreringsHjemmel.FTRL_10_30,
        RegistreringsHjemmel.FTRL_10_31,

        RegistreringsHjemmel.FS_AKT_26_1,
        RegistreringsHjemmel.FS_AKT_26_2,
        RegistreringsHjemmel.FS_AKT_26_3,
        RegistreringsHjemmel.FS_AKT_26_4,
        RegistreringsHjemmel.FS_AKT_26_5,

        RegistreringsHjemmel.FS_HJE_MM_1,
        RegistreringsHjemmel.FS_HJE_MM_2,
        RegistreringsHjemmel.FS_HJE_MM_3,
        RegistreringsHjemmel.FS_HJE_MM_4,
        RegistreringsHjemmel.FS_HJE_MM_5,
        RegistreringsHjemmel.FS_HJE_MM_6,
        RegistreringsHjemmel.FS_HJE_MM_7,
        RegistreringsHjemmel.FS_HJE_MM_8,
        RegistreringsHjemmel.FS_HJE_MM_9,
        RegistreringsHjemmel.FS_HJE_MM_10,
        RegistreringsHjemmel.FS_HJE_MM_11,
        RegistreringsHjemmel.FS_HJE_MM_12,
        RegistreringsHjemmel.FS_HJE_MM_13,
        RegistreringsHjemmel.FS_HJE_MM_14,
        RegistreringsHjemmel.FS_HJE_MM_15,
        RegistreringsHjemmel.FS_HJE_MM_16,
        RegistreringsHjemmel.FS_HJE_MM_17,
        RegistreringsHjemmel.FS_HJE_MM_18,
        RegistreringsHjemmel.FS_HJE_MM_19,
        RegistreringsHjemmel.FS_HJE_MM_20,
        RegistreringsHjemmel.FS_HJE_MM_21,
        RegistreringsHjemmel.FS_HJE_MM_22,
        RegistreringsHjemmel.FS_ORT_HJE_MM_1,
        RegistreringsHjemmel.FS_ORT_HJE_MM_2,
        RegistreringsHjemmel.FS_ORT_HJE_MM_3,
        RegistreringsHjemmel.FS_ORT_HJE_MM_4,
        RegistreringsHjemmel.FS_ORT_HJE_MM_5,
        RegistreringsHjemmel.FS_ORT_HJE_MM_6,
        RegistreringsHjemmel.FS_ORT_HJE_MM_7,
        RegistreringsHjemmel.FS_ORT_HJE_MM_8,
        RegistreringsHjemmel.FS_ORT_HJE_MM_9,
        RegistreringsHjemmel.FS_ORT_HJE_MM_10,
        RegistreringsHjemmel.FS_ORT_HJE_MM_11,
        RegistreringsHjemmel.FS_ORT_HJE_MM_12,
        RegistreringsHjemmel.FS_ORT_HJE_MM_13,
        RegistreringsHjemmel.FS_ORT_HJE_MM_14,
        RegistreringsHjemmel.FS_ORT_HJE_MM_15,
        RegistreringsHjemmel.FS_ORT_HJE_MM_16,
        RegistreringsHjemmel.FS_ORT_HJE_MM_17,
        RegistreringsHjemmel.FS_ORT_HJE_MM_18,
        RegistreringsHjemmel.FS_ORT_HJE_MM_19,
        RegistreringsHjemmel.FS_ORT_HJE_MM_20,
        RegistreringsHjemmel.FS_ORT_HJE_MM_21,

        RegistreringsHjemmel.FS_HA_MM_1,
        RegistreringsHjemmel.FS_HA_MM_2,
        RegistreringsHjemmel.FS_HA_MM_3,
        RegistreringsHjemmel.FS_HA_MM_4,
        RegistreringsHjemmel.FS_HA_MM_5,
        RegistreringsHjemmel.FS_HA_MM_6,
        RegistreringsHjemmel.FS_HA_MM_7,
        RegistreringsHjemmel.FS_HA_MM_8,
        RegistreringsHjemmel.FS_HA_MM_9,
        RegistreringsHjemmel.FS_HA_MM_10,
        RegistreringsHjemmel.FS_HA_MM_11,
        RegistreringsHjemmel.FS_HA_MM_12,
        RegistreringsHjemmel.FS_HA_MM_13,

        RegistreringsHjemmel.FS_SH_1,

        RegistreringsHjemmel.FS_MOK_1,
        RegistreringsHjemmel.FS_MOK_2,
        RegistreringsHjemmel.FS_MOK_3,
        RegistreringsHjemmel.FS_MOK_4,
        RegistreringsHjemmel.FS_MOK_5,
        RegistreringsHjemmel.FS_MOK_6,
        RegistreringsHjemmel.FS_MOK_7,
        RegistreringsHjemmel.FS_MOK_8,
        RegistreringsHjemmel.FS_MOK_9,
        RegistreringsHjemmel.FS_MOK_10,
        RegistreringsHjemmel.FS_MOK_11,
        RegistreringsHjemmel.FS_MOK_12,
        RegistreringsHjemmel.FS_MOK_13,
        RegistreringsHjemmel.FS_MOK_14,

        RegistreringsHjemmel.FTRL_21_3,
        RegistreringsHjemmel.FTRL_21_7,
        RegistreringsHjemmel.FTRL_21_8,
        RegistreringsHjemmel.FTRL_21_10,
        RegistreringsHjemmel.FTRL_21_12,
        RegistreringsHjemmel.FTRL_22_12,
        RegistreringsHjemmel.FTRL_22_13,
        RegistreringsHjemmel.FTRL_22_14,
        RegistreringsHjemmel.FTRL_22_17,

        RegistreringsHjemmel.FVL_11,
        RegistreringsHjemmel.FVL_12,
        RegistreringsHjemmel.FVL_16,
        RegistreringsHjemmel.FVL_17,
        RegistreringsHjemmel.FVL_18_19,
        RegistreringsHjemmel.FVL_21,
        RegistreringsHjemmel.FVL_24,
        RegistreringsHjemmel.FVL_25,
        RegistreringsHjemmel.FVL_28,
        RegistreringsHjemmel.FVL_29,
        RegistreringsHjemmel.FVL_30,
        RegistreringsHjemmel.FVL_31,
        RegistreringsHjemmel.FVL_32,
        RegistreringsHjemmel.FVL_33,
        RegistreringsHjemmel.FVL_35,
        RegistreringsHjemmel.FVL_41,
        RegistreringsHjemmel.FVL_42,

        RegistreringsHjemmel.TRRL_2,
        RegistreringsHjemmel.TRRL_9,
        RegistreringsHjemmel.TRRL_10,
        RegistreringsHjemmel.TRRL_11,
        RegistreringsHjemmel.TRRL_12,
        RegistreringsHjemmel.TRRL_14,
    )
)

